
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Gebo Admin Panel - Login Page</title>

        <!-- Bootstrap framework -->
        <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap-responsive.min.css" />
        <!-- theme color-->
        <link rel="stylesheet" href="/lib/css/blue.css" />
        <!-- tooltip -->    
        <link rel="stylesheet" href="/lib/qtip2/jquery.qtip.min.css" />
        <!-- main styles -->
        <link rel="stylesheet" href="/lib/css/style.css" />

        <!-- Favicons and the like (avoid using transparent .png) -->
        <link rel="shortcut icon" href="favicon.ico" />
        <link rel="apple-touch-icon-precomposed" href="icon.png" />

        <!--[if lte IE 8]>
            <script src="/lib/js/ie/html5.js"></script>
                        <script src="/lib/js/ie/respond.min.js"></script>
        <![endif]-->

    </head>
    <body class="login_page">

        <div class="login_box">

            <form  method="post" id="login_form">
                <div class="top_b">Faça login para entrar</div>   

                <?php if ($this->flashMessenger() != '<div class="sticky-queue top-right" style="width: auto;"></div>') : ?>
                    <div class="alert alert-error alert-login">
                        <strong>Usuário ou senha inválidos!</strong>
                    </div>

                <?php endif; ?>


                <div class="cnt_b">
                    <div class="formRow">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-user"></i></span><input type="text" id="username" name="email" placeholder="Usuário"  />
                        </div>
                    </div>
                    <div class="formRow">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-lock"></i></span><input type="password" id="password" name="senha" placeholder="Senha"  />
                        </div>
                    </div>

                </div>
                <div class="btm_b clearfix">
                    <button class="btn btn-inverse pull-right" type="submit">Entrar</button>
                </div>  
            </form>

            <form  method="post" action="/admin/auth/esqueci" id="pass_form" style="display:none">
                <div class="top_b">Não consegue entrar? Sem problemas!</div>    
                <div class="alert alert-info alert-login">
                    Entre com seu endereço de e-mail para receber uma nova senha
                </div>
                <div class="cnt_b">
                    <div class="formRow clearfix">
                        <div class="input-prepend">
                            <span class="add-on">@</span><input type="text" name="email" placeholder="Seu endereço de e-mail" />
                        </div>
                    </div>
                </div>
                <div class="btm_b tac">
                    <button class="btn btn-inverse" type="submit">Recuperar Senha</button>
                </div> 

                <span class="linkform" style="display:none"><a href="#login_form">Volte para o login</a></span>
            </form>

            <div class="links_b links_btm clearfix">
                <span class="linkform"><a href="#pass_form">Esqueceu a senha?</a></span>
                <span class="linkform" style="display:none">Não me interessa, <a href="#login_form">voltar para tela de login</a></span>
            </div>  
        </div>

        <script src="/lib/js/jquery.min.js"></script>
        <script src="/lib/js/jquery.actual.min.js"></script>
        <script src="/lib/validation/jquery.validate.min.js"></script>
        <script src="/lib/validation/localization/messages_ptbr.js"></script>
        <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function() {

                //* boxes animation
                form_wrapper = $('.login_box');
                $('.linkform a,.link_reg a').on('click', function(e) {
                    var target = $(this).attr('href'),
                            target_height = $(target).actual('height');
                    $(form_wrapper).css({
                        'height': form_wrapper.height()
                    });
                    $(form_wrapper.find('form:visible')).fadeOut(400, function() {
                        form_wrapper.stop().animate({
                            height: target_height
                        }, 500, function() {
                            $(target).fadeIn(400);
                            $('.links_btm .linkform').toggle();
                            $(form_wrapper).css({
                                'height': ''
                            });
                        });
                    });
                    e.preventDefault();
                });

                //* validation
                $('#login_form').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    rules: {
                        email: {required: true, minlength: 3},
                        senha: {required: true, minlength: 3}
                    },
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    errorPlacement: function(error, element) {
                        $(element).closest('div').append(error);
                    }
                });

                $('#pass_form').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    rules: {
                        email: {required: true, minlength: 3}
                    },
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    errorPlacement: function(error, element) {
                        $(element).closest('div').append(error);
                    }
                });
            });
        </script>
    </body>
</html>
