<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>waPanel</title>

        <!-- Bootstrap framework -->
        <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap-responsive.min.css" />
        <!-- gebo blue theme-->
        <link rel="stylesheet" href="/lib/css/blue.css" id="link_theme" />
        <!-- breadcrumbs-->
        <link rel="stylesheet" href="/lib/jBreadcrumbs/css/BreadCrumb.css" />
        <!-- tooltips-->
        <link rel="stylesheet" href="/lib/qtip2/jquery.qtip.min.css" />
        <!-- notifications -->
        <link rel="stylesheet" href="/lib/sticky/sticky.css" />    
        <!-- splashy icons -->
        <link rel="stylesheet" href="/lib/img/splashy/splashy.css" />
        <!-- upload -->
        <link rel="stylesheet" href="/lib/plupload/js/jquery.plupload.queue/css/plupload-gebo.css" />
        <!-- code prettify -->
        <link rel="stylesheet" href="/lib/google-code-prettify/prettify.css" />	
        <!-- colorbox -->
        <link rel="stylesheet" href="/lib/colorbox/colorbox.css" />
        <!-- enhanced select -->
        <link rel="stylesheet" href="/lib/chosen/chosen.css" />
        <!-- main styles -->
        <link rel="stylesheet" href="/lib/css/style.css" />

        <!-- jQuery UI theme-->
        <link rel="stylesheet" href="/lib/jquery-ui/css/Aristo/Aristo.css" />
        <!-- datepicker -->
        <link rel="stylesheet" href="/lib/datepicker/datepicker.css" />
        <!-- tag handler -->
        <link rel="stylesheet" href="/lib/tag_handler/css/jquery.taghandler.css" />
        <!-- nice form elements -->
        <link rel="stylesheet" href="/lib/uniform/Aristo/uniform.aristo.css" />
        <!-- 2col multiselect -->
        <link rel="stylesheet" href="/lib/multiselect/css/multi-select.css" />
        <!-- enhanced select -->
        <link rel="stylesheet" href="/lib/chosen/chosen.css" />
        <!-- upload -->
        <link rel="stylesheet" href="/lib/plupload/js/jquery.plupload.queue/css/plupload-gebo.css" />
        <!-- colorbox -->
        <link rel="stylesheet" href="/lib/colorbox/colorbox.css" />
        <!-- colorpicker -->
        <link rel="stylesheet" href="/lib/colorpicker/css/colorpicker.css" />	

        <!-- main styles -->
        <link rel="stylesheet" href="/lib/css/style.css" />
        <link rel="stylesheet" href="/lib/css/money_application.css" />

        <!-- Fullcalendar-->
        <link rel="stylesheet" href="/lib/fullcalendar/fullcalendar.css" />		
        <link rel="stylesheet" href="/css/upload.css" />		

        <script src="/lib/js/jquery.min.js"></script>

        <!-- smart resize event -->
        <script src="/lib/js/jquery.debouncedresize.min.js"></script>
        <!-- hidden elements width/height -->
        <script src="/lib/js/jquery.actual.min.js"></script>
        <!-- js cookie plugin -->
        <script src="/lib/js/jquery.cookie.min.js"></script>
        <!-- main bootstrap js -->
        <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <!-- tooltips -->
        <script src="/lib/qtip2/jquery.qtip.min.js"></script>
        <!-- jBreadcrumbs -->
        <script src="/lib/jBreadcrumbs/js/jquery.jBreadCrumb.1.1.min.js"></script>
        <!-- fix for ios orientation change -->
        <script src="/lib/js/ios-orientationchange-fix.js"></script>
        <!-- scrollbar -->
        <script src="/lib/antiscroll/antiscroll.js"></script>
        <script src="/lib/antiscroll/jquery-mousewheel.js"></script>
        <!-- lightbox -->
        <script src="/lib/colorbox/jquery.colorbox.min.js"></script>
        <!-- common functions -->
        <script src="/lib/js/gebo_common.js"></script>
        <!-- datatable -->
        <script src="/lib/datatables/jquery.dataTables.min.js"></script>
        <script src="/lib/datatables/extras/Scroller/media/js/Scroller.min.js"></script>

        <!-- code prettifier -->
        <script src="/lib/google-code-prettify/prettify.min.js"></script>
        <!-- plupload and all it's runtimes and the jQuery queue widget (attachments) -->
        <script src="/lib/plupload/js/plupload.full.js"></script>
        <script src="/lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.full.js"></script>
        <!-- autosize textareas (new message) -->
        <script src="/lib/js/forms/jquery.autosize.min.js"></script>
        <!-- touch events for jquery ui-->
        <script src="/lib/js/forms/jquery.ui.touch-punch.min.js"></script>
        <!-- sticky messages -->
        <script src="/lib/sticky/sticky.min.js"></script>

        <!-- masked inputs -->
        <script src="/lib/js/forms/jquery.inputmask.min.js"></script>
        <!-- textarea limiter/counter -->
        <script src="/lib/js/forms/jquery.counter.min.js"></script>
        <!-- timepicker -->
        <script src="/lib/datepicker/bootstrap-timepicker.min.js"></script>
        <!-- tag handler -->
        <script src="/lib/tag_handler/jquery.taghandler.min.js"></script>
        <!-- input spinners -->
        <script src="/lib/js/forms/jquery.spinners.min.js"></script>
        <!-- styled form elements -->
        <script src="/lib/uniform/jquery.uniform.min.js"></script>
        <!-- animated progressbars -->
        <script src="/lib/js/forms/jquery.progressbar.anim.js"></script>
        <!-- multiselect -->
        <script src="/lib/multiselect/js/jquery.multi-select.min.js"></script>
        <!-- enhanced select (chosen) -->
        <script src="/lib/chosen/chosen.jquery.min.js"></script>
        <!-- TinyMce WYSIWG editor -->
        <script src="/lib/tiny_mce/jquery.tinymce.js"></script>
        <!-- colorpicker -->
        <script src="/lib/colorpicker/bootstrap-colorpicker.js"></script>
        <!-- password strength checker -->
        <script src="/lib/complexify/jquery.complexify.min.js"></script>
        <!-- form functions -->
        <script src="/lib/fullcalendar/fullcalendar.js"></script>

        <!-- multi-column layout -->
        <script src="/lib/js/jquery.imagesloaded.min.js"></script>
        <script src="/lib/js/jquery.wookmark.js"></script>
        <!-- responsive table -->
        <script src="/lib/js/jquery.mediaTable.min.js"></script>
        <!-- small charts -->
        <script src="/lib/js/jquery.peity.min.js"></script>
        <!-- charts -->
        <script src="/lib/flot/jquery.flot.min.js"></script>
        <script src="/lib/flot/jquery.flot.resize.min.js"></script>
        <script src="/lib/flot/jquery.flot.pie.min.js"></script>
        <!-- calendar -->
        <!-- sortable/filterable list -->
        <script src="/lib/list_js/list.min.js"></script>
        <script src="/lib/list_js/plugins/paging/list.paging.js"></script>

        <script src="/lib/validation/jquery.validate.min.js"></script>
        <script src="/lib/validation/localization/messages_ptbr.js"></script>
        <script src="/js/upload.js"></script>
        <script src="/js/validacoes.js"></script>
        <script src="/lib/js/application.js"></script>


        <!-- Favicon -->
        <!--<link rel="shortcut icon" href="favicon.ico" />-->

        <!--[if lte IE 8]>
            <link rel="stylesheet" href="/lib/css/ie.css" />
            <script src="/lib/js/ie/html5.js"></script>
                        <script src="/lib/js/ie/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <div id="maincontainer" class="clearfix">
            <!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="/index">waPanel</a>
                            <ul class="nav user_menu pull-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img class="user_avatar" alt="" src="/lib/img/user_avatar.png"> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/auth/logout">Sair</a></li>
                                        <li><a href="javascript:void(0)" class="reset_layout">Resetar posições</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
                                <span class="icon-align-justify icon-white"></span>
                            </a>
                            <nav>
                                <div class="nav-collapse">
                                    <ul class="nav">
                                        <li>
                                            <a href="/admin/index"><i class="icon-home icon-white"></i> <?php echo $this->translate('MENU_HOME'); ?></a>
                                        </li>
                                        <li>
                                            <a href="/admin/noticias"><i class="icon-file icon-white"></i> <?php echo $this->translate('MENU_NOTICIAS'); ?></a>
                                        </li>
                                        <li>
                                            <a href="/admin/banners"><i class="icon-fullscreen icon-white"></i> <?php echo $this->translate('MENU_BANNERS'); ?></a>
                                        </li>
                                        <li>
                                            <a href="/admin/albuns"><i class="icon-user icon-white"></i> <?php echo $this->translate('MENU_ALBUNS'); ?></a>
                                        </li>
                                        <li>
                                            <a href="/admin/configuracoes"><i class="icon-wrench icon-white"></i> <?php echo $this->translate('MENU_CONFIGURACOES'); ?></a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>


            <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                    <?php echo $this->flashMessenger(); ?>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>
