<div class="span3">

    <ul class="nav nav-list well">
        <li><a href="/historico">Histórico</a></li>
        <li class="divider"></li>
        <li><a href="/missao">Missão</a></li>
        <li class="divider"></li>
        <li><a href="/visao">Visão</a></li>
        <li class="divider"></li>
        <li><a href="/valores">Conjunto de valores</a></li>
        <li class="divider"></li>
        <li><a href="/objetivos">Objetivos</a></li>
    </ul>

</div>