<div class="row-fluid">

    <?php echo $this->partial('menuInterno.phtml'); ?>

    <div class="span9">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/historico">Instituto</a> <span class="divider">&raquo;</span></li>
            <li class="active">Histórico</li>
        </ul>

        <h3>Histórico</h3>

        <img src="/img/inauguracao1.jpg" width="350" alt="" class="flt-left" style="margin-right: 10px;"/>

        <p>
            O IVB - Instituto Vicentino´s do Brasil foi fundado no final de 2006, iniciando suas atividades em 12/03/2007.
        </p>

        <p>
            Seu compromisso é com a valorização do ser humano, contribuindo para o desenvolvimento sustentável da comunidade, 
            através da capacitação educacional, social e cultural, melhorando as perspectivas de futuro da comunidade.
        </p>

        <p>
            Sua atuação, a principio, estará pautado na educação, cultura e esportes, disponibilizando de profissionais 
            capacitados para o bom desenvolvimento das atividades e motivando a participação voluntária.
        </p>

        <p>
            Na educação, oferecerá cursos de informática básica e cursos profissionalizantes como Desenho Industrial, 
            Projeto e Decoração de Interiores e Operação de Máquinas Injetoras.
        </p>

        <p>
            Na área cultural, disponibiliza curso de Pintura técnica, onde busca aprimorar os talentos individuais, dando 
            oportunidade de aprendizado de novas técnicas, Pintura Terapêutica como forma de tratamento e acompanhamento 
            psicológico a jovens e adolescentes, além de participação em projetos que reforcem a necessidade de uma nova 
            cultura ambiental.
        </p>

        <p>
            Na área esportiva, será implantada uma escola de futebol a qual atenderá mais de 300 crianças de diversas faixas 
            etárias, buscando minimizar as situações de risco.Valorização da idéia de que “um mundo melhor é possível a partir 
            da vontade humana”.
        </p>

    </div>
</div>
