<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=302723586524209";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<div class="row-fluid">
    <div id="slide" class="carousel slide">
        <ol class="carousel-indicators">
            <?php
            $i = 0;
            foreach ($this->banners as $banner) :
                ?>
                <li data-target="#slide" data-slide-to="<?php echo $i ?>" <?php echo ($i == 0 ? 'class="active"' : ''); ?>></li>
                <?php
                $i++;
            endforeach;
            ?>
        </ol>

        <div class="carousel-inner">
            <?php
            $j = 0;
            foreach ($this->banners as $banner) :
                ?>
                <div class="item <?php echo ($j == 0 ? 'active' : ''); ?>">
                    <img src="/<?php echo $banner->caminho; ?>" alt="<?php echo $banner->nome; ?>" width="979" height="242"/>
                </div>
                <?php
                $j++;
            endforeach;
            ?>
        </div>
        <a class="left carousel-control" href="#slide" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#slide" data-slide="next">&rsaquo;</a>

    </div>
</div>

<div class="row-fluid">
    <div class="span9">
        <div class="row-fluid">
            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>Notícias</span></div>
                    <div class="content-body">

                        <?php $i = 0;
                        foreach ($this->noticias as $noticia) : ?>
                            <h3><?php echo $noticia->titulo; ?></h3>
                            <p>
    <?php echo strip_tags($noticia->texto); ?> <a href="/noticias/single/id/<?php echo $noticia->id; ?>">[Veja mais]</a>
                            </p>

                            <?php echo ($i == 0 ? '<hr/>' : '') ?>
    <?php $i++;
endforeach; ?>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/noticias" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>Inauguração</span></div>
                    <div class="content-body">
                        <img src="/img/inauguracao.jpg" class="flt-left"/>
                        <p>
                            O IVB - Instituto Vicentino´s do Brasil foi fundado no final de 2006, iniciando suas atividades 
                            em 12/03/07.
                            Seu compromisso é com a valorização do ser humano, contribuindo para o 
                            desenvolvimento ... <a href="/historico">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/historico" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>

                <img src="/img/ppo.jpg" />

            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>PSB - Projeto Saúde e Beleza</span></div>
                    <div class="content-body">
                        <img src="/img/psb-index.jpg" style="width: 174px; height: 130px;" class="flt-left"/>
                        <p>
                            A manicure e pedicure é a profissional responsável pelo embelezamento das unhas 
                            das mãos e dos pés, por meio de técnicas de manipulação de instrumentos ...
                            <a href="/projeto-saude-e-beleza">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/projeto-saude-e-beleza" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>PID - Projeto de Inclusão Digital</span></div>
                    <div class="content-body">
                        <img src="/img/pid-bloco.jpg" class="flt-left"/>
                        <p>
                            O IVB tem a consciência de que tanto no presente quanto no futuro, a ignorância por parte dos 
                            cidadãos no uso da linguagem tecnológica da informática, cria um abismo ... 
                            <a href="/projeto-de-inclusao-digital">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/projeto-de-inclusao-digital" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span3">
        <div class="fb-like-box" 
             data-href="https://www.facebook.com/InstitutoVicentinos?fref=ts" 
             data-width="225" 
             data-height="330"
             data-show-faces="true" 
             data-header="true" 
             data-stream="false" 
             data-show-border="true">
        </div>
    </div>
</div>