<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=302723586524209";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<div class="row-fluid">
    <div id="slide" class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#slide" data-slide-to="0" class="active"></li>
            <li data-target="#slide" data-slide-to="1"></li>
            <li data-target="#slide" data-slide-to="2"></li>
            <li data-target="#slide" data-slide-to="3"></li>
        </ol>

        <div class="carousel-inner">
            <div class="item active">
                <img src="/img/slide.jpg" alt=""/>
            </div>

            <div class="item">
                <img src="/img/banner_2.jpg" alt="" width="979" height="242"/>
            </div>

            <div class="item">
                <img src="/img/banner_3.jpg" alt="" width="979" height="242"/>
            </div>

            <div class="item">
                <img src="/img/banner_4.jpg" alt="" width="979" height="242"/>
            </div>
        </div>
        <a class="left carousel-control" href="#slide" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#slide" data-slide="next">&rsaquo;</a>

    </div>
</div>

<div class="row-fluid">
    <div class="span9">
        <div class="row-fluid">
            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>Notícias</span></div>
                    <div class="content-body">
                        <h3>O IVB tem um novo Site</h3>
                        <p>
                            O IVB - Instituto Vicentino´s do Brasil foi fundado no final de 2006, iniciando suas atividades 
                            em 12/03/07.<a href="/historico">[veja mais]</a>
                        </p>

                        <hr/>

                        <h3>Título da notícia principal</h3>
                        <p>
                            O IVB - Instituto Vicentino´s do Brasil foi fundado no final de 2006, iniciando suas atividades 
                            em 12/03/07... <a href="#">[veja mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="#" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>Inauguração</span></div>
                    <div class="content-body">
                        <img src="/img/inauguracao.jpg" class="flt-left"/>
                        <p>
                            O IVB - Instituto Vicentino´s do Brasil foi fundado no final de 2006, iniciando suas atividades 
                            em 12/03/07.
                            Seu compromisso é com a valorização do ser humano, contribuindo para o 
                            desenvolvimento ... <a href="/historico">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/historico" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>

                <img src="/img/ppo.jpg" />

            </div>
        </div>

        <div class="row-fluid">
            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>PPO - Projeto Pintando Oportunidade</span></div>
                    <div class="content-body">
                        <img src="/img/ppo-bloco.jpg" class="flt-left"/>
                        <p>
                            O fato de ser considerada uma ótima terapia, a pintura em tela contribui para garantir aos 
                            indivíduos momentos de bem-estar numa das mais fascinantes e criativas atividades ...
                            <a href="/projeto-pintando-oportunidade">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/projeto-pintando-oportunidade" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="content-block">
                    <div class="content-block-header"><span>PID - Projeto de Inclusão Digital</span></div>
                    <div class="content-body">
                        <img src="/img/pid-bloco.jpg" class="flt-left"/>
                        <p>
                            O IVB tem a consciência de que tanto no presente quanto no futuro, a ignorância por parte dos 
                            cidadãos no uso da linguagem tecnológica da informática, cria um abismo ... 
                            <a href="/projeto-de-inclusao-digital">[saiba mais]</a>
                        </p>
                    </div>
                    <div class="content-block-footer clearfix">
                        <a href="/projeto-de-inclusao-digital" class="mais"><img src="/img/mais.jpg" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="span3">
        <div class="fb-like-box" 
             data-href="https://www.facebook.com/InstitutoVicentinos?fref=ts" 
             data-width="225" 
             data-height="330"
             data-show-faces="true" 
             data-header="true" 
             data-stream="false" 
             data-show-border="true">
        </div>
    </div>
</div>