<div class="row-fluid">
    
    <?php echo $this->partial('menuInterno.phtml'); ?>

    <div class="span9">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/historico">Instituto</a> <span class="divider">&raquo;</span></li>
            <li class="active">Missão</li>
        </ul>

        <h3>Missão</h3>

        <p>
            Contribuir com o desenvolvimento sustentável da comunidade através de ações multidisciplinares 
            capacitando pessoas e gerando novas possibilidades de trabalho, renda e perspectivas para o futuro.
        </p>
    </div>
</div>