<div class="row-fluid">

    <?php echo $this->partial('menuInterno.phtml'); ?>

    <div class="span9">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/historico">Instituto</a> <span class="divider">&raquo;</span></li>
            <li class="active">Objetivos</li>
        </ul>

        <h3>Objetivos</h3>

        <ul>
            <li>Participar do combate à evasão escolar</li>
            <li>Ser facilitador para a qualificação profissional</li>
            <li>Estimular o desenvolvimento pessoal e as habilidades básicas para o aumento da empregabilidade</li>
            <li>Contribuir para a redução de crianças em situação de vulnerabilidade social</li>
            <li>Contribuir para formação da família e de cidadãos</li>
            <li>Desenvolver a educação nutricional, ambiental e para a cidadania</li>
            <li>Promover estudos para o desenvolvimento e a implantação de novas tecnologias sociais e produtivas</li>
        </ul>

    </div>
</div>
