<div class="row-fluid">
    
    <?php echo $this->partial('menuInterno.phtml'); ?>

    <div class="span9">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/historico">Instituto</a> <span class="divider">&raquo;</span></li>
            <li class="active">Conjunto de Valores</li>
        </ul>

        <h3>Conjunto de valores</h3>

        <ul>
            <li>A dignidade do ser humano é um bem a ser preservado.</li>
            <li>A cidadania se constrói a partir da família e é reforçada pela ação educacional.</li>
            <li>Toda pessoa, física ou jurídica, pode contribuir para a melhoria da sua comunidade.</li>
            <li>Educação para o trabalho e para a vida são as chaves do futuro.</li>
            <li>Desigualdade e violência se combatem com educação e oportunidades.</li>
        </ul>

    </div>
</div>
