<div class="row-fluid">
    
    <?php echo $this->partial('menuInterno.phtml'); ?>

    <div class="span9">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/historico">Instituto</a> <span class="divider">&raquo;</span></li>
            <li class="active">Visão</li>
        </ul>

        <h3>Visão</h3>

        <p>
            Um mundo melhor é possível a partir da vontade humana.
        </p>
    </div>
</div>
