<div class="container">
    <div class="row-fluid">
        <div class="span12">

            <div id="jCrumbs" class="breadCrumb module">
                <ul>
                    <li>
                        <a href="/admin"><i class="icon-home"></i></a>
                    </li>
                    <li>
                        <a href="/admin/albuns">Listagem de Albuns</a>
                    </li>
                    <li>
                        <a href="#">Gerenciar Fotos do Album</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <h3>Gerenciando fotos do Album -> <?php echo $this->album->nome; ?> </h3>

        <br/>

        <form enctype="multipart/form-data" id="exemplo2" method="post">
            <div class="clearfix">
                <input name="file[]" type="file" multiple />
                <input type="hidden" name="idAlbum" value="<?php echo $this->album->id; ?>" />

                <input type="submit" value="Enviar Seleciondos" id="upload" class="btn btn-success" />
            </div>
        </form>

        <div class="progress progress-success">
            <div class="bar"></div>
        </div>

        <div id="messages"></div>
        <div id="fotos"></div>
    </div>

</div>

<script>
    $(document).ready(function() {

        $("#upload").click(function() {
            $("#fotos").html('<div style="padding: 50px; text-align: center;"><img src="/lib/img/ajax_loader.gif" title="Carregando..."></div>');
        });

        $("#fotos").html('<div style="padding: 50px; text-align: center;"><img src="/lib/img/ajax_loader.gif" title="Carregando..."></div>');
        $("#fotos").load('/admin/albuns/lista-fotos/id/<?php echo $this->album->id; ?>');

        $(function() {
            $("#exemplo2").epAjaxUpload({
                progressBar: ".bar",
                progressCounter: "#progress .progressbar-label",
                url: '/admin/albuns/add-foto',
                sucesso: function() {
                    $("#fotos").load('/admin/albuns/lista-fotos/id/<?php echo $this->album->id; ?>');
                    $('form')[0].reset();
                    $('.bar').css({width: 0});
                    $("#messages").prepend('<div class="alert alert-info"><button type="button"' + 
                                        ' class="close" data-dismiss="alert">×</button><strong>'+
                                        'Upload concluído com sucesso!</strong></div>');
                },
                error: function(msgError) {
                    $("#fotos").append('<p class="epAjaxUpload-error">Desculpe, ocorreu um erro ao fazer upload!</p>');
                }
            });
        });

        $(".delete").live('click', function() {
            $("#fotos").html('<div style="padding: 50px; text-align: center;"><img src="/lib/img/ajax_loader.gif" title="Carregando..."></div>');
            var id = $(this).attr('id');
            var album = $(this).attr('album');
            $.ajax({
                url: '/admin/albuns/remove-foto/id/' + id + '/album/' + album,
                type: 'POST',
                dataType: "json",
                success: function(data) {
                    $("#fotos").load('/admin/albuns/lista-fotos/id/<?php echo $this->album->id; ?>');
                    $("#messages").html('<div class="alert alert-info"><button type="button"' + 
                                        ' class="close" data-dismiss="alert">×</button><strong>'+
                                        'Removido com sucesso!</strong></div>');
                },
                error: function(msgError) {

                }
            });
        });
    });

</script>
