<div class="row-fluid">
    <img src="/img/banner_2.jpg" alt="Projeto de Inclusão Digital (PID)"/>

    <div class="espaco"></div>

    <p>
        O IVB tem a consciência de que tanto no presente quanto no futuro, a 
        ignorância por parte dos cidadãos no uso da linguagem tecnológica da informática, 
        cria um abismo cultural muito grande entre as pessoas, mesmo estando inseridas no mesmo ambiente. 
    </p>

    <p>
        “Dentro de pouco tempo um cidadão que não conhecer a linguagem básica de informática, será considerado um analfabeto".
    </p>

    <p>
        O PID - Projeto de Inclusão Digital, tem como objetivo oportunizar a população 
        mais carente da sociedade o acesso à tecnologia básica da informática, oferecendo 
        gratuitamente os cursos de Windows, Word, Excel, Digitação e Internet. 
        Com a democratização do acesso a informática e com ajuda da tecnologia disponível, 
        buscam-se a integração entre educação, tecnologia e cidadania, visando à transformação social.
    </p> 

    <p>
        Promover a inclusão social da população excluída digitalmente, utilizando 
        as tecnologias da informação como instrumento de construção e exercício da cidadania.
        Para o IVB, Incluir digitalmente não é apenas "alfabetizar" as pessoas em informática, 
        mas também melhorar os quadros sociais a partir do manuseio dos computadores. 
        Não apenas ensiná-las a usar o computador, mas melhorar as condições de vida 
        de uma determinada região ou comunidade.
    </p>
    
    <p> 
        São 15 turmas de 10 alunos num total de 150 alunos, atingindo crianças a partir de 11 anos, 
        adolescentes, jovens e adultos, das escolas Estaduais do município, funcionários da empresa 
        Vicentino´s do Brasil e seus familiares, nos horários de manhã, tarde e noite.
    </p>
</div>