<div class="row-fluid">
    <img src="/img/banner_3.jpg" alt="Projeto de Inclusão Digital (PID)"/>

    <div class="espaco"></div>

    <h4>OBJETIVOS GERAIS DO PBB</h4>

    <p>
        Atualmente nas escolas se tem como problemática principal a metodologia de ensino, 
        visto que a maioria dos alunos não consegue ter um bom desenvolvimento, por uma série 
        de fatores, de ordem educacional, social, comunitária e também familiar.
    </p>

    <img src="/img/pbb-01.jpg" alt="Projeto Batendo um Bolão" style="float: left; margin-right: 8px;"/>

    <p>
        O “PBB – Projeto Batendo um Bolão” visa contribuir no desenvolvimento intelectual 
        e físico das crianças, criando condições para a melhoria da qualidade de vida e 
        o estímulo ao convívio social e coletivo, buscando assim resgatar valores esquecidos, 
        construindo cidadãos conscientes de seu papel na sociedade, tendo conhecimento de seus 
        deveres e direitos.
    </p>

    <p>
        Já se identificou hoje que o esporte é um instrumento eficaz e competente 
        como fator de desenvolvimento humano, dispondo de vários benefícios, tanto 
        para indivíduos como para a coletividade. É importante mudar o conceito sobre 
        o papel que a atividade esportiva e de lazer desempenham em nossas vidas.
        A educação é base do equilíbrio social e da cidadania. A formação dos cidadãos 
        começa na infância e precisa ser bem orientada para que se desenvolvam na 
        adolescência e juventude se solidificando assim na fase adulta. Portanto, 
        as iniciativas sociais que buscam oferecer oportunidades e experiências positivas
        e saudáveis às pessoas são consideradas prioritárias em muitos países, 
        inclusive no Brasil. Entre as camadas sociais menos favorecidas, 
        as dificuldades na formação do cidadão se potencializam, em virtude 
        da falta de oportunidades, da discriminação e de outros fatores.
    </p>

    <p>
        O esporte, especificamente o futebol, integrador social por excelência, 
        amenizador de conflitos sociais e provedor direto e indireto de empregos, 
        foi o mecanismo encontrado pelo programa em questão, para contribuir na formação 
        de cidadãos plenos e conscientes de suas responsabilidades.
    </p>

    <img src="/img/pbb-02.jpg" alt="Projeto Batendo um Bolão" style="float: left; margin-right: 8px;"/>

    <p>
        O PBB – Projeto Batendo um Bolão objetiva contribuir na formação de cidadãos, 
        buscando a inclusão social através de iniciativas e ações técnico-didático-pedagógicas 
        voltadas ao equilíbrio dos processos de interação social cooperativa e competitiva de 
        forma consciente e reflexiva. Temos hoje questões sociais que interferem significativamente 
        na qualidade de vida de nossas crianças, afetando diretamente o desenvolvimento escolar e social. 
        O esporte é um dos meios mais viáveis e eficazes para o desenvolvimento psico-social 
        da criança em questão.
    </p>

    <p>
        Sendo assim, desenvolvemos o “PBB - Projeto Batendo um Bolão”, com futebol 
        de campo, suíço e salão, que envolverá crianças, adolescentes e jovens com 
        idade de 6 a 16 anos, ambos pertencentes às comunidades do próprio município 
        que, infelizmente, se encontram em propensas inclinações à marginalização 
        devido ao seu estado de exclusão social eminente.
        O projeto visa atender 350 alunos dentre as diversas modalidades e faixas 
        etárias, no futebol de campo, suíço e salão.
    </p>

    <h4>OBJETIVOS ESPECÍFICOS</h4>

    <ul>
        <li>Promover o intercâmbio social, a autonomia e a solidariedade através do futebol;</li>
        <li>Promover o aprendizado em grupo, a cooperação e a parceria;</li>
        <li>Incentivar o futebol como alternativo às drogas e tempos ociosos, estimulando à vida saudável e prevenção de doenças;</li>
        <li>Proporcionar a oportunidade à participação em eventos esportivos e culturais como gincanas, festivais, torneios, campeonatos;</li>
        <li>Proporcionar a escolha por condutas adequadas em relação às pessoas e ao ambiente vivenciado;</li>
        <li>Combater a evasão escolar e a repetência;</li>
        <li>Estimular a prática regular de atividades físicas;</li>
        <li>Promover a descontração e o relaxamento físico e mental;</li>
        <li>Estimular o trabalho em grupo e a convivência comunitária.</li>
    </ul>

    <h4>CRITÉRIOS</h4>

    <p>
        Os critérios exigidos para participar do projeto: estar devidamente 
        matriculado na escola e no projeto, ter de 06 a 16 anos.
        Pré-estabelecemos ao matriculado que haverá um acompanhamento das notas, onde o 
        aluno deverá atingir uma média mínima de 7,0 e presença escolar mínima de 75% 
        para que possa freqüentar as aulas, incentivando-o no desenvolvimento escolar,
        além de gerar a oportunidade de descobrirem suas habilidades e formação de cidadãos.
    </p>

    <h4>ESTRUTURA</h4>

    <p>
        O IVB – Instituto Vicentino´s do Brasil disponibiliza um coordenador 
        exclusivo para o projeto além de Professores e Estagiários, também 
        campos e quadras esportivas e os materiais necessários ao projeto.
    </p>

    <h4>DICAS DO IVB</h4>

    <ul>
        <li>Respeite os seus semelhantes indistintamente;</li>
        <li>Respeite a Natureza;</li>
        <li>Diga não ao álcool e as drogas;</li>
        <li>Procure dormir pelo menos 8 horas por dia;</li>
        <li>Evite refrigerante, prefira água e sucos naturais;</li>
        <li>Evite falar palavrões;</li>
        <li>Em qualquer circunstância, cumprimente o adversário;</li>
        <li>Honre sempre a camisa que está vestindo;</li>
        <li>Dê o máximo de si na escola, estude sempre;</li>
        <li>Procure se alimentar de forma balanceada;</li>
        <li>Ouça sempre o que os mais experientes têm a dizer;</li>
        <li>Procure tomar pelo menos 8 copos de água por dia;</li>
    </ul>
    
    <div class="espaco"></div>
</div>