<div class="row-fluid">
    <img src="/img/banner_4.jpg" alt="Projeto de Inclusão Digital (PID)"/>

    <div class="espaco"></div>
    
    <p>
        O fato de ser considerada uma ótima terapia, a pintura em tela contribui 
        para garantir aos indivíduos momentos de bem-estar numa das mais fascinantes 
        e criativas atividades artísticas, o Instituto Vicentinos do Brasil oferecerá 
        para a comunidade o Projeto Pintando Oportunidade (PPO). Coordenado pela Psicóloga e 
        Artista Plástica Patrícia Cesco Martinelli - CRP 08/12615. O projeto conta com 36
        vagas para oficina de pintura em tela.
    </p>

    <img src="/img/ppo-01.jpg" alt="Projeto Pintando Oportunidade" style="float: left; margin-right: 8px;"/>
    
    <p>
        O programa funcionará com duas abordagens metodológicas, tendo duas turmas funcionando 
        com o enfoque da pintura técnica e didática, voltada à aprendizagem pedagógica 
        profissionalizante de pintores da área abstrata e acadêmica, e outras duas turmas 
        de Arte terapia, visando o tratamento de transtornos emocionais e comportamentais 
        intermediados pela vivência da pintura terapêutica.

    </p>
    
    <p>
        O objetivo do projeto é promover o desenvolvimento das capacidades cognitivas
        e sensoriais dos integrantes, proporcionando à pessoa assistida uma intervenção 
        orientada para a qualidade de vida, numa linha habilitadora e integracional. 
        Estes são os objetivos gerais do PPO, que são complementados por outros, mais específicos, 
        de cunho pedagógico ou interventivo na área comportamental, dependendo do 
        enfoque metodológico de cada turma.

    </p>
    
    <p>
        Deste modo, a um nível pedagógico, procura-se potenciar a capacidade de 
        aprendizagem e criatividade dos integrantes; proporcionar-lhes a sua adaptação 
        social, hábitos de trabalho e o desenvolvimento de suas aptidões artísticas. 
        A nível terapêutico é um trabalho de estimulação, um espaço para desenvolvimento 
        psicosocial, afetivo e cognitivo dos participantes, utilizando atividades, lúdicas 
        e recreativas, para o estímulo à inteligência, à criatividade e à autonomia, 
        criando oportunidades para o desenvolvimento de relações mais satisfatórias e 
        conseqüente desenvolvimento pessoal. 
    </p>
    
    <img src="/img/ppo-02.jpg" alt="Projeto Pintando Oportunidade" style="float: left; margin-right: 8px;"/>
    
    <p>
        A seleção dos alunos será feita pela coordenadoria do projeto para as turmas 
        de pintura terapêutica, sendo necessária à presença do responsável em caso
        de menoridade para ser feita a triagem psicológica. A seleção para as turmas 
        de pintura técnica, consta de uma prova de aptidão técnica de desenho e pintura,
        sendo contemplados os 20 indivíduos que melhor satisfizerem as exigências da prova 
        e para a turma de pintura terapêutica os 16 indivíduos que mais apresentem as 
        características específicas para serem beneficiados com este tipo de tratamento.
    </p>

    <p>

        No final do curso será oferecido certificado com comprovação de hora atividade 
        em pintura em tela.
        Mais informações sobre a seleção com Adriana Storto, coordenadora de projetos 
        do Instituto Vicentino´s do Brasil pelo fone (44) 3232-9278 em horário comercial. 
        A oficina, que constitui um espaço criativo e acolhedor, que reabilita o indivíduo, 
        introduzindo-o no circuito de trabalho e ocupação terapêutica, ajudará os indivíduos 
        a manterem-se socialmente integradas e emocionalmente compensados.
    </p>

</div>