<div class="row-fluid">
    <img src="/img/psb.jpg" alt="Projeto Saúde e Beleza (PSB)"/>

    <div class="espaco"></div>

    <h4>JUSTIFICATIVA</h4>

    <p>
        A manicure e pedicure é a profissional responsável pelo embelezamento das unhas das 
        mãos e dos pés, por meio de técnicas de manipulação de instrumentos e equipamentos 
        específicos de trabalho, respeitando os critérios de higiene, a ética e a estética 
        da profissão.
    </p>

    <p>
        Para tanto, executa tarefas referentes à limpeza, ao polimento e à esmaltagem das unhas 
        dos clientes, utilizando instrumentos e substâncias adequados para dar-lhes beleza e aspecto 
        tratado, além de dominar técnicas de assepsia, tais como a esterilização e descontaminação dos 
        instrumentos de trabalho para conservá-los em condições de uso e evitar o risco de transmissão 
        de doenças. 
    </p>

    <p>
        Portanto, o presente Curso oferece capacitação profissional e pessoal das adolescentes, jovens 
        e adultas em situação de vulnerabilidade social capacitando-as a se tornarem proativas na construção 
        de uma sociedade mais fraterna com justiça social.
    </p>

    <h4>PÚBLICO ALVO</h4>

    <p>
        Destinado exclusivamente para o público feminino, a partir de 16 anos, interessadas em atuar como manicures e pedicures.
    </p>

    <h4>DURAÇÃO</h4>

    <p>
        Quatro meses, sendo que as aulas serão ministradas duas vezes por semana com duas horas de duração.
    </p>

    <h4>OBJETIVO GERAL</h4>

    <p>
        Propiciar condições as alunas para o desenvolvimento de competências profissionais e empreendedoras 
        necessárias ao exercício da atividade de manicure e pedicure visando à melhoria na diversidade produtiva 
        pela complementação da renda familiar mediante atividades psico-pedagógica exercida por instrutora devidamente 
        qualificada.
    </p>

    <h4>OBJETIVO ESPECÍFICO</h4>

    <p>
        Intensificar o processo de inclusão produtiva das alunas no mercado de trabalho, tornando-as cidadãs 
        responsáveis e profissionais aptas a trabalhar em salões de beleza ou como autônoma.
    </p>

    <h4>Competências Profissionais a serem desenvolvidas</h4>

    <ul>
        <li>Adotar normas de conduta ética e um padrão de imagem profissional, tendo como referência as diretrizes estabelecidas por órgãos reguladores da área;</li>
        <li>Limpar, desinfetar e esterilizar os instrumentos de trabalho, utilizando produtos e procedimentos específicos, de acordo com as normas de assepsia, para conservá-los em condições de uso e evitar contaminação;</li>
        <li>Executar procedimentos de corte, lixamento, emoliência, curetagem, cutilagem do eponíqueo (cutícula), assegurando a saúde e a integridade do cliente;</li>
        <li>Esmaltar lâminas, respeitando padrões técnicos e estéticos da área;</li>
        <li>Aplicar técnicas de higiene e segurança, seguindo as normas da legislação vigente;</li>
        <li>Preparar e manter atualizada a agenda de trabalho, de modo a agilizar o atendimento.</li>
    </ul>

    <h4>RESULTADOS ESPERADOS</h4>

    <p>
        Possibilitar uma complementação da renda, facilitar o ingresso no mercado de trabalho e desenvolver senso 
        empreendedor nas adolescentes, jovens e adultas assistidas pela instituição, através da capacitação profissional 
        nas áreas de manicure e pedicure.
    </p>

    <h4>AVALIAÇÃO</h4>

    <p>
        Será realizada durante as aulas ministradas, avaliando e observando o desempenho de cada aluna se tem aptidão 
        para a profissão, e também será realizada uma prova teórica e prática, com base no material didático criado
        pelo IVB.
    </p>

    <div class="espaco"></div>
</div>