<div class="row-fluid">
    <div class="span12">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/home">Instituto</a> <span class="divider">&raquo;</span></li>
            <li><a href="/noticias">Notícias</a> <span class="divider">&raquo;</span></li>
        </ul>

        <h3>Notícias</h3>
    </div>
</div>

<div class="row-fluid">
    <?php foreach ($this->noticias as $noticia) : ?>
        <div>
            <h4><?php echo $noticia->titulo; ?></h4>
            <p><?php echo strip_tags($noticia->texto); ?></p> <a href="/noticias/single/id/<?php echo $noticia->id; ?>">[Veja mais]</a>
        </div>
    
        <hr/>
    <?php endforeach; ?>
</div>
