<div class="row-fluid">
    <div class="span12">

        <ul class="breadcrumb">
            <li>Você está em: </li>
            <li><a href="/home">Instituto</a> <span class="divider">&raquo;</span></li>
            <li><a href="/noticias">Notícias</a> <span class="divider">&raquo;</span></li>
            <li class="active"><?php echo $this->noticia->titulo; ?></li>
        </ul>

        <h3><?php echo $this->noticia->titulo; ?></h3>
    </div>
</div>

<div class="row-fluid">
    <?php echo $this->noticia->texto; ?>
</div>
