<div class="container">
    <div class="row-fluid">
        <div class="span12">

            <div id="jCrumbs" class="breadCrumb module">
                <ul>
                    <li>
                        <a href="/admin"><i class="icon-home"></i></a>
                    </li>
                    <li>
                        <a href="#">Listagem de Banners</a>
                    </li>
                </ul>
            </div>

            <a href="/admin/banners/add" class="btn btn-success">+ Novo Banner</a>

        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th width="10%" class="align-center">#id</th>
                        <th>Nome</th>
                        <th class="align-center">Ativo</th>
                        <th width="15%" class="align-center">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo (sizeof($this->banners) == 0 ? '<tr><td colspan="4">Nenhum registro encontrado!</td></tr>' : ''); ?>

                    <?php foreach ($this->banners as $banner) : ?>
                        <tr>
                            <td class="align-center"><?php echo $banner->id; ?></td>
                            <td><?php echo $banner->nome; ?></td>
                            <td class="align-center"><?php echo ($banner->ativo == 1 ? 'Sim' : 'Não'); ?></td>
                            <td class="align-center">
                                <?php if ($banner->ativo == 1) : ?>
                                    <a href="/admin/banners/inativar/id/<?php echo $banner->id; ?>" class="icon-arrow-down" alt="Desativar Banner" title="Desativar Banner"></a>
                                <?php endif; ?>

                                <?php if ($banner->ativo == 0) : ?>
                                    <a href="/admin/banners/ativar/id/<?php echo $banner->id; ?>" class="icon-arrow-up" alt="Ativar Banner" title="Ativar Banner"></a>
                                <?php endif; ?>
                                    
                                &nbsp;
                                <a href="/admin/banners/delete/id/<?php echo $banner->id; ?>" class="icon-trash confirm" alt="Excluir Banner" title="Excluir Banner"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>